name: CI/CD Workflow

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd LB-Projekt-M210/frontend
          npm install

      - name: Build project
        run: |
          cd LB-Projekt-M210/frontend
          npm run build
